# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    mongodb_uri: '%env(MONGODB_URI)%'
    db_host: '127.0.0.1'
    db_port: 3306
    db_name: 'skillswap'
    db_user: 'root'
    db_password: ''

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # MongoDBService registration
    App\Service\MongoDBService:
        arguments:
            $parameterBag: '@parameter_bag'
            $httpClient: '@http_client'

    # DatabaseService for MySQL direct access
    App\Service\DatabaseService:
        arguments:
            $params: '@parameter_bag'

    # DataSeederService registration
    App\Service\DataSeederService:
        arguments:
            $mongodb: '@App\Service\MongoDBService'
            $passwordHasher: '@security.user_password_hasher'
            
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
